import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  contentContainer: {
    paddingBottom: 24,
    gap: 10,
  },
  pageHeader: {
    gap: 10,
    paddingTop: 2,
  },
  heroCard: {
    borderWidth: 1,
    borderRadius: 24,
    padding: 14,
    gap: 12,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  heroHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  backButton: {
    width: 40,
    height: 40,
    borderWidth: 1,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroTitleBlock: {
    flex: 1,
    gap: 2,
  },
  heroEyebrow: {
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1,
  },
  heroTitle: {
    fontSize: 18,
    fontWeight: '900',
    lineHeight: 23,
  },
  heroIconWrap: {
    width: 64,
    height: 64,
    borderWidth: 1,
    borderRadius: 20,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroIconCore: {
    width: 48,
    height: 48,
    borderRadius: 14,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  heroChart: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 4,
  },
  heroBar: {
    width: 6,
    borderRadius: 4,
  },
  heroShimmer: {
    position: 'absolute',
    top: -10,
    bottom: -10,
    width: 30,
    backgroundColor: 'rgba(255,255,255,0.2)',
  },
  heroMetaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  metaPill: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 7,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  metaPillText: {
    fontSize: 11,
    fontWeight: '700',
  },
  filterBlock: {
    gap: 8,
  },
  inlineRow: {
    gap: 8,
  },
  filterChip: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 11,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  filterChipText: {
    fontSize: 12,
    fontWeight: '700',
  },
  monthChip: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  monthChipText: {
    fontSize: 11,
    fontWeight: '700',
  },
  rangeRow: {
    flexDirection: 'row',
    gap: 10,
  },
  rangeCard: {
    flex: 1,
    borderWidth: 1,
    borderRadius: 14,
    padding: 10,
    gap: 2,
  },
  rangeLabel: {
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  rangeValue: {
    fontSize: 14,
    fontWeight: '800',
  },
  summaryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  gridSpanFull: {
    width: '100%',
  },
  gridSpanHalf: {
    width: '48%',
  },
  gridBlockHalf: {
    width: '48%',
  },
  summaryCard: {
    borderWidth: 1,
    borderRadius: 20,
    padding: 12,
    gap: 8,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
  },
  summaryTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 8,
  },
  summaryFrame: {
    gap: 2,
  },
  inlineStatPill: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  inlineStatText: {
    fontSize: 11,
    fontWeight: '800',
  },
  summaryMetaRow: {
    flexDirection: 'row',
    gap: 8,
  },
  summaryMetaCard: {
    flex: 1,
    borderWidth: 1,
    borderRadius: 14,
    padding: 10,
    gap: 3,
  },
  summaryMetaLabel: {
    fontSize: 10,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.7,
  },
  summaryMetaValue: {
    fontSize: 14,
    fontWeight: '800',
  },
  summaryLabel: {
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.9,
  },
  summaryValue: {
    fontSize: 22,
    fontWeight: '900',
  },
  settlementCard: {
    borderWidth: 1,
    borderRadius: 20,
    padding: 12,
    gap: 10,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
  },
  settlementHeader: {
    gap: 8,
  },
  settlementCopy: {
    gap: 4,
  },
  settlementHeadline: {
    fontSize: 17,
    fontWeight: '900',
    lineHeight: 22,
  },
  settlementDirection: {
    fontSize: 12,
    fontWeight: '700',
  },
  settlementBadgePressable: {
    alignSelf: 'flex-start',
  },
  settlementBadge: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  settlementBadgeText: {
    fontSize: 12,
    fontWeight: '800',
  },
  settlementLockHint: {
    fontSize: 12,
    lineHeight: 14,
  },
  settlementMetaGrid: {
    flexDirection: 'row',
    gap: 10,
  },
  settlementMetaCard: {
    flex: 1,
    borderWidth: 1,
    borderRadius: 14,
    padding: 10,
    gap: 3,
  },
  settlementMetaLabel: {
    fontSize: 10,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  settlementMetaValue: {
    fontSize: 13,
    fontWeight: '800',
  },
  readOnlyBanner: {
    borderWidth: 1,
    borderRadius: 14,
    padding: 10,
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
  },
  readOnlyText: {
    flex: 1,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
  },
  warningCard: {
    borderWidth: 1,
    borderRadius: 16,
    padding: 10,
    flexDirection: 'row',
    gap: 8,
  },
  warningCopy: {
    flex: 1,
    gap: 6,
  },
  warningText: {
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '600',
  },
  tabShell: {
    borderWidth: 1,
    borderRadius: 18,
    padding: 4,
    flexDirection: 'row',
    gap: 4,
  },
  tabButton: {
    flex: 1,
    borderRadius: 12,
    paddingVertical: 9,
    alignItems: 'center',
  },
  tabInner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  tabText: {
    fontSize: 12,
    fontWeight: '800',
  },
  sectionCard: {
    borderWidth: 1,
    borderRadius: 20,
    padding: 12,
    gap: 10,
  },
  dashboardGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    alignItems: 'flex-start',
  },
  glassCard: {
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 4,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 10,
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  labelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  metricLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  inlineInfoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '900',
  },
  infoButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  infoBubble: {
    borderWidth: 1,
    borderRadius: 14,
    padding: 10,
  },
  infoBubbleText: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '600',
  },
  mileageBreakdownRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  mileageMiniCard: {
    borderWidth: 1,
    borderRadius: 14,
    padding: 10,
    gap: 4,
  },
  mileageMiniLabel: {
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  mileageMiniValue: {
    fontSize: 15,
    fontWeight: '900',
  },
  mileageStack: {
    gap: 8,
  },
  mileageInfoCard: {
    borderWidth: 1,
    borderRadius: 14,
    padding: 10,
    gap: 4,
  },
  mileageValue: {
    fontSize: 16,
    fontWeight: '900',
  },
  mileageEditorRow: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'flex-end',
  },
  mileageEditorInputWrap: {
    flex: 1,
    gap: 4,
  },
  mileageInput: {
    borderWidth: 1,
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 15,
    fontWeight: '800',
  },
  mileageEditorLabel: {
    fontSize: 10,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  mileageSaveButton: {
    width: 42,
    height: 42,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  helperText: {
    fontSize: 11,
    lineHeight: 13,
  },
  doubleMetricRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  metricCard: {
    borderRadius: 16,
    padding: 12,
    width: '48%',
  },
  metricLabel: {
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  metricValue: {
    fontSize: 18,
    fontWeight: '900',
    marginTop: 6,
  },
  metricHint: {
    fontSize: 11,
    lineHeight: 14,
    marginTop: 4,
  },
  userSplitStack: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  userSplitCard: {
    borderRadius: 16,
    padding: 12,
    gap: 10,
    width: '100%',
  },
  userSplitHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  userSplitName: {
    fontSize: 15,
    fontWeight: '900',
  },
  userSplitBadge: {
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 0.8,
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 999,
  },
  userSplitGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  userMetric: {
    width: '48%',
    gap: 4,
  },
  userMetricLabel: {
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  userMetricValue: {
    fontSize: 14,
    fontWeight: '900',
  },
  emptyBlock: {
    borderRadius: 16,
    padding: 14,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  emptyTitle: {
    fontSize: 14,
    fontWeight: '900',
  },
  flowGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  flowCard: {
    borderWidth: 1,
    borderRadius: 16,
    padding: 12,
    gap: 6,
  },
  flowLabel: {
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  flowValue: {
    fontSize: 16,
    fontWeight: '900',
  },
  fastagUsersRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  fastagUserCard: {
    borderWidth: 1,
    borderRadius: 16,
    padding: 12,
    gap: 5,
    width: '48%',
  },
  expenseSectionStack: {
    gap: 10,
  },
  fastagUserName: {
    fontSize: 14,
    fontWeight: '900',
  },
  fastagLine: {
    fontSize: 12,
    lineHeight: 15,
  },
  fastagBalanceText: {
    fontSize: 14,
    fontWeight: '800',
    marginTop: 2,
  },
  expenseSectionCard: {
    borderWidth: 1,
    borderRadius: 16,
    padding: 12,
    gap: 8,
  },
  otherSectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  otherSectionTitle: {
    fontSize: 14,
    fontWeight: '900',
  },
  otherSectionValue: {
    fontSize: 16,
    fontWeight: '900',
  },
  expenseList: {
    borderRadius: 12,
    overflow: 'hidden',
  },
  expenseRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 10,
  },
  expenseRowLabel: {
    flex: 1,
    fontSize: 13,
    fontWeight: '600',
  },
  expenseRowValue: {
    fontSize: 13,
    fontWeight: '800',
  },
  datePickerCard: {
    marginTop: 14,
    borderWidth: 1,
    borderRadius: 22,
    padding: 14,
    gap: 10,
  },
  datePickerTitle: {
    fontSize: 15,
    fontWeight: '900',
  },
  datePickerDone: {
    borderWidth: 1,
    borderRadius: 14,
    paddingVertical: 11,
    alignItems: 'center',
  },
  datePickerDoneText: {
    fontSize: 14,
    fontWeight: '800',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.48)',
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  modalCard: {
    borderWidth: 1,
    borderRadius: 24,
    padding: 18,
    gap: 14,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '900',
  },
  modalText: {
    fontSize: 14,
    lineHeight: 20,
  },
  modalActions: {
    gap: 10,
  },
  modalPrimaryButton: {
    borderRadius: 16,
    paddingVertical: 13,
    alignItems: 'center',
  },
  modalPrimaryText: {
    fontSize: 14,
    fontWeight: '900',
  },
  modalSecondaryButton: {
    borderWidth: 1,
    borderRadius: 16,
    paddingVertical: 13,
    alignItems: 'center',
  },
  modalSecondaryText: {
    fontSize: 14,
    fontWeight: '800',
  },
});
